services:
  laravel-app:
    image: ${DOCKERHUB_USERNAME}/hrms-backend:latest
    container_name: hrms-backend
    restart: unless-stopped
    env_file: .env # Reads from local host directory
    volumes:
      - hrms-public-assets:/var/www/public
    networks:
      - hrms-tier

  nginx:
    image: nginx:alpine
    container_name: hrms-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - hrms-public-assets:/var/www/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - hrms-tier
    depends_on:
      - laravel-app

  mysql-db:
    image: mysql:8.0
    container_name: hrms-database
    restart: unless-stopped
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hrms-tier

networks:
  hrms-tier:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  hrms-public-assets:
    driver: local
